---
title: "Evaluating and Synthesizing Quantitative Research"
subtitle: "CRMW Lecture 1"
author: "Charles Lanfear"
date: "30 Jan 2025<br>Updated: `r gsub(' 0', ' ', format(Sys.Date(), format='%d %b %Y'))`"
output:
  xaringan::moon_reader:
    css: "../assets/cam-css.css"
    lib_dir: libs
    nature:
      highlightStyle: tomorrow-night-bright
      highlightLines: true
      countIncrementalSlides: false
      beforeInit: "../assets/cam_macros.js"
      titleSlideClass: ["center","top"]
---


# Background

.text-125[
You have been hired as a team of social policy consultants
]

--
.text-125[
&nbsp;

The policy-maker wants an answer to the following question:

** *Do Community Violence Interventions (CVI) reduce violence?* **

&nbsp;
]

--

.text-125[

Your colleagues have already identified a collection of relevant studies, but they haven't obtained them or evaluated them yet
]

--

.text-125[
&nbsp;

Time is short: *You're meeting the policy-maker at the end of today's seminar!*
]

---

# The Maryland Scale

* **Level 5**: Units have been **randomised** into treatment and control groups

--

* **Level 4**: Exploits **quasi-randomness** so that treatment and control groups credibly differ only in their exposure to the random allocation of treatment

--

* **Level 3**: Comparison of outcomes in treated group **before and after** an intervention, and a **comparison group** used to provide a **comparable counterfactual**

--

* **Level 2**: Use of **adequate control variables** and either...
   * A post-intervention comparison of treated groups with untreated groups
   * A before-and-after comparison of only the treated group

--

* **Level 1**: Either...
   * A post-intervention comparison of treated groups with untreated groups
   * A before-and-after comparison of only the treated group

---

# Your Task

.text-125[
Use the Cambridge Library, Google Scholar, or other resources to:

1. Locate the study on the slide, then
2. Sort it into one of the "Maryland levels" based on its design
3. Write your group #, first author, year, and rating on slip<sup>1</sup>

.footnote[[1] e.g.: "2 MacDonald (2016) 5"]


If there is disagreement among group members, *record the disagreement for discussion*

]

---

## STUDY 1

.text-125[
Braga, A.A., Hureau, D.M., & Papachristos, A.V. (2014) Deterring gang-involved gun violence: Measuring the impact of Boston's Operation Ceasefire on street gang behavior. *Journal of Quantitative Criminology*, 30.
]

---

## STUDY 2

.text-125[
Fox, A.M., Katz, C.M., Choate, D.E., & Hedberg, E.C. (2015) Evaluation of the Phoenix TRUCE project: A replication of Chicago CeaseFire. *Justice Quarterly*, 32(1)
]

---

## STUDY 3

.text-125[
Bhatt M.P., Heller, .S.B, Kapustin, M., Bertrand, M., & Blattman, C. (2024) Predicting and preventing gun violence: An experimental evaluation of READI Chicago. *Quarterly Journal of Economics*, 139(1)
]

---

## STUDY 4

.text-125[
Hureau, D.M., Braga, A.A., Lloyd, T., & Winship, C. (2023) Streetwork at the crossroads: An evaluation of a street gang outreach intervention and holistic appraisal of the research evidence. *Criminology*, 61
]

---

## STUDY 5

.text-125[
Corburn, J., Boggan, D., Muttaqi, K., & Vaughn, S. (2022) Preventing urban firearm homicides during COVID-19: Preliminary results from three cities with the Advance Peace program. *Journal of Urban Health*, 99
]

---

## STUDY 6

.text-125[
Picard-Fritsche, S. & Cerniglia, L. (2013) *Testing a public health approach to gun violence: An evaluation of Crown Heights Save Our Streets, a replication of the Curve Violence model.* New York, NY: Center for Court Innovation
]

---

## STUDY 7

.text-125[
Buggs, S.A., Webster, D.W., & Crifasi, C.K. (2022) Using synthetic control methodology to estimate effects of a Cure Violence intervention in Baltimore, Maryland. *Injury Prevention*, 28
]

---

## STUDY 8

.text-125[
Boyle, D.J., Lanterman, J.L., Pascarella, J.E., & Cheng, C-C. (2010) The impact of Newark's Operation Ceasfire on trauma center gunshot wound admissions. *Justice Research and Policy*, 12(2)
]

---

## STUDY 9

.text-125[
Ross, M.C., Ochoa, EM., & Papachristos, A.V. (2023) Evaluating the impact of a street outreach intervention on participant involvement in gang violence. *PNAS*, 120(46)
]

---

## STUDY 10

.text-125[
Webster, D.W., Whitehill, J.M., Vernick, J.S., & Curriero, F.C. (2012) Effects of Baltimore's Safe Streets program on gun violence: A replication of Chicago's CeaseFire program. *Journal of Urban Health*, 90(1)
]

---

## STUDY 11

.text-125[
Braga, A.A., Kennedy, D.M., Waring, E.J., & Piehl, A.M. (2001) Problem-oriented policing, deterrence, and youth violence: An evaluation of Boston's Operation Ceasefire. *Journal of Research in Crime and Delinquency*, 38(3)
]

---

## STUDY 12

.text-125[
Park, J., Schoenberg, F.P., Bertozzi, A.L., & Brantingham, P.J. (2021) Investigating clustering and violence interruption in gang-related violent crime data using spatial-temporal point processes with covariates. *Journal of the American Statistical Association*, 116(536)
]

---

## STUDY 13

.text-125[
Brantingham, P.J., Tita, G., & Herz, D. (2021) The impact of the City of Los Angeles Mayor's Office of Gang Reduction and Youth Development (GRYD) comprehensive strategy on crime in the City of Los Angeles. *Justice Evaluation Journal*, 4(2)
]

---

## STUDY 14

.text-125[
Wilson, J.M. & Chermak, S. (2011) Community-driven violence reduction programs: Examining Pittsburgh's One Vision One Life. *Criminology & Public Policy*, 10(4)
]

---
class: inverse

# Wrap-Up

&nbsp;

## [Seminar today!](https://www.crim.cam.ac.uk/events/lent-term-public-seminar-professor-joe-murray)


