---
title: "Seminar 4: Conducting experiments"
description: "Experimental methods in criminology"
author: "Andrzej Uhl"
date: "2025-02-20"
draft: false
---

Lecture Slides on Moodle

Required reading:

* Bachman, R., & Schutt, R.K. (2017). *The Practice of Research in Criminology and Criminal Justice*, 6th ed., London: Sage.
(Read chapter 7, ‘Experimental designs’, pp. 176-206)
* Exum, M. L. (2002). The application and robustness of the rational choice perspective in the study of intoxicated and angry intentions to aggress. *Criminology*, 40(4), 933-966.  (Read pp. 939-947)
* Fehr, E., & Gächter, S. (2002). Altruistic punishment in humans. *Nature*, 415(6868), 137-140.
* An Introduction to Factorial Survey Experiments – Part 1: Introduction: https://www.youtube.com/watch?v=5xfuqaCWJ6w 


Further reading:

* Factorial survey experiments
   * Wallander, L. (2009). 25 years of factorial surveys in sociology: A review. *Social Science Research*, 38(3), 505-520.
   * Wikström, P.-O. H., Oberwittler, D., Treiber, K & Hardie, B. (2012). *Breaking Rules: The Social and Situational Dynamics of Young People’s Urban Crime*. OUP Oxford. Available on iDiscover. (Read Chapter 8)
* Natural experiments
   * Fisman, R., & Miguel, E. (2007). Corruption, norms, and legal enforcement: Evidence from diplomatic parking tickets. Journal of Political Economy, 115(6), 1020-1048.
* Immersive experiments
   * Barnum, T. C., Herman, S., van Gelder, J. L., Ribeaud, D., Eisner, M., & Nagin, D. S. (2024). Reactive guardianship: Who intervenes? How? And why? *Criminology* 62(3), 587-618.
* Field experiments
   * Pager, D. (2003). The mark of a criminal record. *American Journal of Sociology*, 108(5), 937-975.
* Conjoint experiments
   * Schwarz, S., Baum, M. A., & Cohen, D. K. (2020). (Sex) crime and punishment in the# MeToo era: How the public views rape. *Political Behavior* 44, 75-104.
* Randomised controlled trials
   * Sherman, L. W., & Berk, R. A. (1984). The specific deterrent effects of arrest for domestic assault. *American Sociological Review* 49(2), 261–272.
* Simulating experiments in observational data
  * Loeffler, C. E., & Nagin, D. S. (2022). The impact of incarceration on recidivism. *Annual Review of Criminology*, 5(1), 133-152.

