---
title: "Seminar 2: Writing Up Quantitative Research"
description: "Basic guidelines for presenting quantitative data and results"
author: "Charles Lanfear"
date: "2024-02-01"
draft: false
---

[Lecture Slides](https://clanfear.github.io/ioc_crmw/_lectures/2_writing-up-quantitative-research/slides_writing-up-quantitative-research.html)

Required reading:

* Bryman, A. (2015) *Social Research Methods*, 5th ed., Oxford: Oxford University Press. Chapter 28.
   * Access ebook via iDiscover

* Matsueda, R. (2019) ‘Structuring a conventional empirical social science article.’ Unpublished.
   * Access via Moodle or [here](https://clanfear.github.io/ioc_crmw/_lectures/2_writing-up-quantitative-research/reading/S6 Matsueda (2019) Structuring a conventional empirical social science article.pdf)

Further reading:

* Wentz, E. (2014)  *How to Design, Write, and Present a Successful Dissertation Proposal*, London: SAGE.
 https://doi.org/10.4135/9781506374710

* Fallon, M. (2016) *Writing up Quantitative Research in the Social and Behavioral Sciences*, Rotterdam : SensePublishers.
   * Access ebook via iDiscover

* American Psychological Association (2020) *Publication Manual of the American Psychological Association : The Official Guide to APA Style*, Seventh ed., Washington, DC : American Psychological Association

* Miller, J.E. (2015) *The Chicago Guide to Writing about Numbers* (2nd ed.). Chicago: University of Chicago Press.

* McCloskey, D. (2019) *Economical Writing: Thirty-Five Rules for Clear and Persuasive Prose* (3rd ed.). Chicago: University of Chicago Press.

* Becker, H.S. (2020) *Writing for Social Scientists: How to Start and Finish Your Thesis, Book, or Article* (3rd ed.). Chicago: University of Chicago Press.
