---
title: "Seminar 1: Quantitative Data Management"
subtitle: "**Optional for Crim 1 students**"
description: "Dealing with real world data"
author: "Charles Lanfear"
date: "2024-01-25"
draft: false
---

[Lecture Slides](https://clanfear.github.io/ioc_crmw/_lectures/1_quantitative-data-management/slides_quantitative-data-management.html)

Data for lab:

* [London Crime data (.zip)](https://clanfear.github.io/ioc_crmw/_data/dpu-crime-met-2022.zip)
* [LSOA Indices of Deprivation (.csv)](https://clanfear.github.io/ioc_crmw/_data/imd2019lsoa.csv)
* [LSOA Population Density (.xlsx)](https://clanfear.github.io/ioc_crmw/_data/land-area-population-density-lsoa11-msoa11.xlsx)

In-class code:

* [`1_process-metro.R`](https://clanfear.github.io/ioc_crmw/_lectures/1_quantitative-data-management/activity/code/1_process-metro.R)
* [`2_process-deprivation.R`](https://clanfear.github.io/ioc_crmw/_lectures/1_quantitative-data-management/activity/code/2_process-deprivation.R)

*Note: We did not finish the activity, so in week 3 we will use a pre-built project scaffold!*

Required readings:

* Quartz. *The Quartz guide to bad data.* https://github.com/Quartz/bad-data-guide
   * “An exhaustive reference to problems seen in real-world data along with suggestions on how to resolve them.”
   * Don’t read this thoroughly, but browse through it a bit!

Further reading and resources:

* Wickham, H. and Grolemund, G. (2022) *R for Data Science.* Sebastopol, CA: O’Reilly. https://r4ds.hadley.nz/ 

* Robinson, D. *Tidy Tuesday live screencasts.* https://www.youtube.com/@safe4democracy/streams 
   * Livestreamed data cleaning and analysis videos. See also https://www.youtube.com/@JuliaSilge 

* Data Carpentry. (2022) *Social Science Curriculum.* https://datacarpentry.org/lessons/#social-science-curriculum 
   * Recommended workshop rather than reading; look for upcoming workshops!


